### ISSUE TITLE
Plugin won't show in Rider 2020.1.0.0

### ISSUE THREAD

**Issue by mterwoord** [matkoch/resharper-xao#23]
Title says it all. I'm trying to install it via Rider, and it wont show in the plugins MarketPlace.
In 2019.x.y.z it worked great.

**Comment by TeaDrivenDev** [comment]
It was updated for 2020.1, but apparently only for the EAP version, not for the final release.

**Comment by matkoch** [comment]
Hey @mterwoord @TeaDrivenDev could you please try again? Sorry for the late response!

https://plugins.jetbrains.com/plugin/12816-xao/update/88280

**Comment by TeaDrivenDev** [comment]
Sorry, a little late here, but it works fine in 2020.1.3, thanks!
